### ISSUE TITLE
Play nicely with solarized light terminal colors

### ISSUE THREAD

**Issue by dazza-codes** [eventbrite/invoke-release#9]
Ubuntu 18.04 has solarized dark and light themes for the terminal, can invoke release detect these color term settings and play nicely with them (or use a third-party library to manage that interface)?

![screen shot 2019-02-12 at 10 55 42 am](https://user-images.githubusercontent.com/240623/52660708-1c48c480-2eb5-11e9-96f0-7970b486aaec.png)
![screen shot 2019-02-12 at 10 56 13 am](https://user-images.githubusercontent.com/240623/52660709-1c48c480-2eb5-11e9-9c43-e3f5d49eda98.png)

**Comment by nickwilliams-eventbrite** [comment]
Sorry for taking so long to see and respond to this. 

I definitely understand the problem you're highlighting, and it does indeed make this difficult to use. However, I'm unaware of any sort of reliable and generic way to detect the theme a terminal is using. Do you know of a way that could be used here?

Absent some way to "detect" this, what we could do is read an optional environment variable `INVOKE_RELEASE_MODE` that defaults to `dark` (to continue existing behavior) and that can be changed to `light` by the user to use alternate colors. What would you think of this solution? Another option is is a command-line argument to change the mode, but that might be tiresome to use every time. An environment variable would be persistent.

**Comment by dazza-codes** [comment]
The env-var is a good idea.  Maybe `click` has some code to handle terminal color schemes or at least detect the terminal background.
- https://click.palletsprojects.com/en/7.x/utils/
- https://click.palletsprojects.com/en/7.x/utils/#ansi-colors
